version: '3.8'
services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=creators
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
volumes:
  postgres:
